# This rule is not used by the project purda itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the purda.colossyan.com.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: purda
    app.kubernetes.io/managed-by: kustomize
  name: purda-editor-role
rules:
- apiGroups:
  - purda.colossyan.com
  resources:
  - purda
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - purda.colossyan.com
  resources:
  - purda/status
  verbs:
  - get
